name: CI
on:
  - push

jobs:
  build:
    name: Build example binary and injector library
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and tests
        run: |
          mkdir -p build && cd build
          cmake ..
          make VERBOSE=1
          LD_PRELOAD=./injector/libinjector.so ./binary/binary
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
